/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "magic-3d-tabs": {
    name: "magic-3d-tabs",
    description: "A beautiful 3D tabs component with perspective effects",
    type: "registry:component",
    files: [{
      path: "src/registry/magic-3d-tabs/magic-3d-tabs.tsx",
      type: "registry:component",
    }],
  },
  "magic-3d-tabs-demo": {
    name: "magic-3d-tabs-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/magic-3d-tabs-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/magic-3d-tabs-demo.tsx")),
  },
}