/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "magic-genie-tabs": {
    name: "magic-genie-tabs",
    description: "macOS-style genie animation with a sleek glass pill nav bar",
    type: "registry:component",
    files: [{
      path: "src/registry/magic-genie-tabs/magic-genie-tabs.tsx",
      type: "registry:component",
    }],
  },
  "magic-genie-tabs-demo": {
    name: "magic-genie-tabs-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/magic-genie-tabs-demo.tsx",
      type: "registry:example",
    }],
    component: React.lazy(() => import("@/registry/examples/magic-genie-tabs-demo.tsx")),
  },
}